// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using addObjectThrowAntherTable.AppContext;

#nullable disable

namespace addObjectThrowAntherTable.Migrations
{
    [DbContext(typeof(Appdbcontext))]
    partial class AppdbcontextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("addObjectThrowAntherTable.Models.session", b =>
                {
                    b.Property<int>("sessionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("sessionId"));

                    b.Property<string>("sessionName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("sessionId");

                    b.ToTable("sessions");
                });

            modelBuilder.Entity("addObjectThrowAntherTable.Models.student", b =>
                {
                    b.Property<int>("studentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("studentId"));

                    b.Property<string>("studentName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("studentId");

                    b.ToTable("students");
                });

            modelBuilder.Entity("sessionstudent", b =>
                {
                    b.Property<int>("sessionssessionId")
                        .HasColumnType("int");

                    b.Property<int>("studentsstudentId")
                        .HasColumnType("int");

                    b.HasKey("sessionssessionId", "studentsstudentId");

                    b.HasIndex("studentsstudentId");

                    b.ToTable("sessionstudent");
                });

            modelBuilder.Entity("sessionstudent", b =>
                {
                    b.HasOne("addObjectThrowAntherTable.Models.session", null)
                        .WithMany()
                        .HasForeignKey("sessionssessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("addObjectThrowAntherTable.Models.student", null)
                        .WithMany()
                        .HasForeignKey("studentsstudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
